[package]
name = "slippery-bastard"
version = "0.1.0"
edition = "2024"

[dependencies]
enigo = "0.3.0"


[package.metadata.packager]
before-packaging-command = "cargo build --release"
product-name = "Slippery Bastard"
identifier = "com.slippery Bastard"
